#!/bin/bash
#
# Usage: bash <(curl -s https://comrad.app/run)
#
# Also at: https://github.com/ComradOrg/Comrad/blob/master/script/micro_installer
#
# For more info, visit: https://github.com/ComradOrg/Comrad#install
#
##


bash <(curl -s https://raw.githubusercontent.com/ComradOrg/Comrad/master/script/install)

